%YAML:1.0
---
# ###### CAMERA PARAMETERS ######
video width: 640
video height: 480
camera fx: 1044.87
camera fy: 1045.69141
camera cx: 320
camera cy: 240

distortion parameters: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -2.7167827743927644e-03, 2.0942424424199252e-01,
       1.1120545920170163e-03, -6.6420567497010334e-03, 0. ]
# ###### TEMPLATE GENERATION SETTINGS ######
model folder: models/
model file ending: ".ply"
only use color modality: 1
in plane rotation starting angle: -45
in plane rotation stopping angle: 45
in plane rotation angle step: 10
distance start: 500
distance stop: 1200
distance step: 50
icosahedron subdivisions: 2
# ###### TEMPLATE DETECTOR SETTINGS ######
detector threshold: 78
percent to pass check: 50
number of poses to compare: 1
distance to match to be considered same object: 45
ratio to determine if group is too small: 35
use depth improvement: 1
depth offset: 30
use icp: 0
icp subsampling factor: 2


