# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mihaipopescu/Desktop/LINE-MOD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mihaipopescu/Desktop/LINE-MOD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake /Users/mihaipopescu/Desktop/LINE-MOD/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mihaipopescu/Desktop/LINE-MOD/CMakeFiles /Users/mihaipopescu/Desktop/LINE-MOD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mihaipopescu/Desktop/LINE-MOD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Detector

# Build rule for target.
Detector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Detector
.PHONY : Detector

# fast build rule for target.
Detector/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/build
.PHONY : Detector/fast

#=============================================================================
# Target rules for targets named Template_Generator

# Build rule for target.
Template_Generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Template_Generator
.PHONY : Template_Generator

# fast build rule for target.
Template_Generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/build
.PHONY : Template_Generator/fast

#=============================================================================
# Target rules for targets named Arcuo_Benchmark

# Build rule for target.
Arcuo_Benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Arcuo_Benchmark
.PHONY : Arcuo_Benchmark

# fast build rule for target.
Arcuo_Benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/build
.PHONY : Arcuo_Benchmark/fast

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

arucoBenchmark.o: arucoBenchmark.cpp.o
.PHONY : arucoBenchmark.o

# target to build an object file
arucoBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/arucoBenchmark.cpp.o
.PHONY : arucoBenchmark.cpp.o

arucoBenchmark.i: arucoBenchmark.cpp.i
.PHONY : arucoBenchmark.i

# target to preprocess a source file
arucoBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/arucoBenchmark.cpp.i
.PHONY : arucoBenchmark.cpp.i

arucoBenchmark.s: arucoBenchmark.cpp.s
.PHONY : arucoBenchmark.s

# target to generate assembly for a file
arucoBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/arucoBenchmark.cpp.s
.PHONY : arucoBenchmark.cpp.s

detector.o: detector.cpp.o
.PHONY : detector.o

# target to build an object file
detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/detector.cpp.o
.PHONY : detector.cpp.o

detector.i: detector.cpp.i
.PHONY : detector.i

# target to preprocess a source file
detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/detector.cpp.i
.PHONY : detector.cpp.i

detector.s: detector.cpp.s
.PHONY : detector.s

# target to generate assembly for a file
detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/detector.cpp.s
.PHONY : detector.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main.cpp.s
.PHONY : main.cpp.s

src/Aruco.o: src/Aruco.cpp.o
.PHONY : src/Aruco.o

# target to build an object file
src/Aruco.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Aruco.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Aruco.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Aruco.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Aruco.cpp.o
.PHONY : src/Aruco.cpp.o

src/Aruco.i: src/Aruco.cpp.i
.PHONY : src/Aruco.i

# target to preprocess a source file
src/Aruco.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Aruco.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Aruco.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Aruco.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Aruco.cpp.i
.PHONY : src/Aruco.cpp.i

src/Aruco.s: src/Aruco.cpp.s
.PHONY : src/Aruco.s

# target to generate assembly for a file
src/Aruco.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Aruco.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Aruco.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Aruco.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Aruco.cpp.s
.PHONY : src/Aruco.cpp.s

src/Benchmark.o: src/Benchmark.cpp.o
.PHONY : src/Benchmark.o

# target to build an object file
src/Benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Benchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Benchmark.cpp.o
.PHONY : src/Benchmark.cpp.o

src/Benchmark.i: src/Benchmark.cpp.i
.PHONY : src/Benchmark.i

# target to preprocess a source file
src/Benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Benchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Benchmark.cpp.i
.PHONY : src/Benchmark.cpp.i

src/Benchmark.s: src/Benchmark.cpp.s
.PHONY : src/Benchmark.s

# target to generate assembly for a file
src/Benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Benchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Benchmark.cpp.s
.PHONY : src/Benchmark.cpp.s

src/CameraViewPoints.o: src/CameraViewPoints.cpp.o
.PHONY : src/CameraViewPoints.o

# target to build an object file
src/CameraViewPoints.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/CameraViewPoints.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/CameraViewPoints.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/CameraViewPoints.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/CameraViewPoints.cpp.o
.PHONY : src/CameraViewPoints.cpp.o

src/CameraViewPoints.i: src/CameraViewPoints.cpp.i
.PHONY : src/CameraViewPoints.i

# target to preprocess a source file
src/CameraViewPoints.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/CameraViewPoints.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/CameraViewPoints.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/CameraViewPoints.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/CameraViewPoints.cpp.i
.PHONY : src/CameraViewPoints.cpp.i

src/CameraViewPoints.s: src/CameraViewPoints.cpp.s
.PHONY : src/CameraViewPoints.s

# target to generate assembly for a file
src/CameraViewPoints.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/CameraViewPoints.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/CameraViewPoints.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/CameraViewPoints.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/CameraViewPoints.cpp.s
.PHONY : src/CameraViewPoints.cpp.s

src/HighLevelLinemod.o: src/HighLevelLinemod.cpp.o
.PHONY : src/HighLevelLinemod.o

# target to build an object file
src/HighLevelLinemod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemod.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemod.cpp.o
.PHONY : src/HighLevelLinemod.cpp.o

src/HighLevelLinemod.i: src/HighLevelLinemod.cpp.i
.PHONY : src/HighLevelLinemod.i

# target to preprocess a source file
src/HighLevelLinemod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemod.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemod.cpp.i
.PHONY : src/HighLevelLinemod.cpp.i

src/HighLevelLinemod.s: src/HighLevelLinemod.cpp.s
.PHONY : src/HighLevelLinemod.s

# target to generate assembly for a file
src/HighLevelLinemod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemod.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemod.cpp.s
.PHONY : src/HighLevelLinemod.cpp.s

src/HighLevelLinemodIcp.o: src/HighLevelLinemodIcp.cpp.o
.PHONY : src/HighLevelLinemodIcp.o

# target to build an object file
src/HighLevelLinemodIcp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemodIcp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemodIcp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemodIcp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemodIcp.cpp.o
.PHONY : src/HighLevelLinemodIcp.cpp.o

src/HighLevelLinemodIcp.i: src/HighLevelLinemodIcp.cpp.i
.PHONY : src/HighLevelLinemodIcp.i

# target to preprocess a source file
src/HighLevelLinemodIcp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemodIcp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemodIcp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemodIcp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemodIcp.cpp.i
.PHONY : src/HighLevelLinemodIcp.cpp.i

src/HighLevelLinemodIcp.s: src/HighLevelLinemodIcp.cpp.s
.PHONY : src/HighLevelLinemodIcp.s

# target to generate assembly for a file
src/HighLevelLinemodIcp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/HighLevelLinemodIcp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/HighLevelLinemodIcp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/HighLevelLinemodIcp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/HighLevelLinemodIcp.cpp.s
.PHONY : src/HighLevelLinemodIcp.cpp.s

src/Kinect2.o: src/Kinect2.cpp.o
.PHONY : src/Kinect2.o

# target to build an object file
src/Kinect2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Kinect2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Kinect2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Kinect2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Kinect2.cpp.o
.PHONY : src/Kinect2.cpp.o

src/Kinect2.i: src/Kinect2.cpp.i
.PHONY : src/Kinect2.i

# target to preprocess a source file
src/Kinect2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Kinect2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Kinect2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Kinect2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Kinect2.cpp.i
.PHONY : src/Kinect2.cpp.i

src/Kinect2.s: src/Kinect2.cpp.s
.PHONY : src/Kinect2.s

# target to generate assembly for a file
src/Kinect2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/Kinect2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/Kinect2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/Kinect2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Kinect2.cpp.s
.PHONY : src/Kinect2.cpp.s

src/ModelBuffer.o: src/ModelBuffer.cpp.o
.PHONY : src/ModelBuffer.o

# target to build an object file
src/ModelBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelBuffer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelBuffer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelBuffer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelBuffer.cpp.o
.PHONY : src/ModelBuffer.cpp.o

src/ModelBuffer.i: src/ModelBuffer.cpp.i
.PHONY : src/ModelBuffer.i

# target to preprocess a source file
src/ModelBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelBuffer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelBuffer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelBuffer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelBuffer.cpp.i
.PHONY : src/ModelBuffer.cpp.i

src/ModelBuffer.s: src/ModelBuffer.cpp.s
.PHONY : src/ModelBuffer.s

# target to generate assembly for a file
src/ModelBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelBuffer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelBuffer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelBuffer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelBuffer.cpp.s
.PHONY : src/ModelBuffer.cpp.s

src/ModelImporter.o: src/ModelImporter.cpp.o
.PHONY : src/ModelImporter.o

# target to build an object file
src/ModelImporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelImporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelImporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelImporter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelImporter.cpp.o
.PHONY : src/ModelImporter.cpp.o

src/ModelImporter.i: src/ModelImporter.cpp.i
.PHONY : src/ModelImporter.i

# target to preprocess a source file
src/ModelImporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelImporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelImporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelImporter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelImporter.cpp.i
.PHONY : src/ModelImporter.cpp.i

src/ModelImporter.s: src/ModelImporter.cpp.s
.PHONY : src/ModelImporter.s

# target to generate assembly for a file
src/ModelImporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/ModelImporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/ModelImporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/ModelImporter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/ModelImporter.cpp.s
.PHONY : src/ModelImporter.cpp.s

src/OpenglRender.o: src/OpenglRender.cpp.o
.PHONY : src/OpenglRender.o

# target to build an object file
src/OpenglRender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/OpenglRender.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/OpenglRender.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/OpenglRender.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/OpenglRender.cpp.o
.PHONY : src/OpenglRender.cpp.o

src/OpenglRender.i: src/OpenglRender.cpp.i
.PHONY : src/OpenglRender.i

# target to preprocess a source file
src/OpenglRender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/OpenglRender.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/OpenglRender.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/OpenglRender.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/OpenglRender.cpp.i
.PHONY : src/OpenglRender.cpp.i

src/OpenglRender.s: src/OpenglRender.cpp.s
.PHONY : src/OpenglRender.s

# target to generate assembly for a file
src/OpenglRender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/OpenglRender.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/OpenglRender.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/OpenglRender.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/OpenglRender.cpp.s
.PHONY : src/OpenglRender.cpp.s

src/PoseDetection.o: src/PoseDetection.cpp.o
.PHONY : src/PoseDetection.o

# target to build an object file
src/PoseDetection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/PoseDetection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/PoseDetection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/PoseDetection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PoseDetection.cpp.o
.PHONY : src/PoseDetection.cpp.o

src/PoseDetection.i: src/PoseDetection.cpp.i
.PHONY : src/PoseDetection.i

# target to preprocess a source file
src/PoseDetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/PoseDetection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/PoseDetection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/PoseDetection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PoseDetection.cpp.i
.PHONY : src/PoseDetection.cpp.i

src/PoseDetection.s: src/PoseDetection.cpp.s
.PHONY : src/PoseDetection.s

# target to generate assembly for a file
src/PoseDetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/PoseDetection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/PoseDetection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/PoseDetection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/PoseDetection.cpp.s
.PHONY : src/PoseDetection.cpp.s

src/TemplateGenerator.o: src/TemplateGenerator.cpp.o
.PHONY : src/TemplateGenerator.o

# target to build an object file
src/TemplateGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/TemplateGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/TemplateGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/TemplateGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TemplateGenerator.cpp.o
.PHONY : src/TemplateGenerator.cpp.o

src/TemplateGenerator.i: src/TemplateGenerator.cpp.i
.PHONY : src/TemplateGenerator.i

# target to preprocess a source file
src/TemplateGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/TemplateGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/TemplateGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/TemplateGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TemplateGenerator.cpp.i
.PHONY : src/TemplateGenerator.cpp.i

src/TemplateGenerator.s: src/TemplateGenerator.cpp.s
.PHONY : src/TemplateGenerator.s

# target to generate assembly for a file
src/TemplateGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/TemplateGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/TemplateGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/TemplateGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/TemplateGenerator.cpp.s
.PHONY : src/TemplateGenerator.cpp.s

src/defines.o: src/defines.cpp.o
.PHONY : src/defines.o

# target to build an object file
src/defines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/defines.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/defines.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/defines.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/defines.cpp.o
.PHONY : src/defines.cpp.o

src/defines.i: src/defines.cpp.i
.PHONY : src/defines.i

# target to preprocess a source file
src/defines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/defines.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/defines.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/defines.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/defines.cpp.i
.PHONY : src/defines.cpp.i

src/defines.s: src/defines.cpp.s
.PHONY : src/defines.s

# target to generate assembly for a file
src/defines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/defines.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/defines.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/defines.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/defines.cpp.s
.PHONY : src/defines.cpp.s

src/utility.o: src/utility.cpp.o
.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/src/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/src/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arcuo_Benchmark.dir/build.make CMakeFiles/Arcuo_Benchmark.dir/src/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

templateGeneration.o: templateGeneration.cpp.o
.PHONY : templateGeneration.o

# target to build an object file
templateGeneration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/templateGeneration.cpp.o
.PHONY : templateGeneration.cpp.o

templateGeneration.i: templateGeneration.cpp.i
.PHONY : templateGeneration.i

# target to preprocess a source file
templateGeneration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/templateGeneration.cpp.i
.PHONY : templateGeneration.cpp.i

templateGeneration.s: templateGeneration.cpp.s
.PHONY : templateGeneration.s

# target to generate assembly for a file
templateGeneration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Template_Generator.dir/build.make CMakeFiles/Template_Generator.dir/templateGeneration.cpp.s
.PHONY : templateGeneration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Arcuo_Benchmark"
	@echo "... Detector"
	@echo "... Main"
	@echo "... Template_Generator"
	@echo "... arucoBenchmark.o"
	@echo "... arucoBenchmark.i"
	@echo "... arucoBenchmark.s"
	@echo "... detector.o"
	@echo "... detector.i"
	@echo "... detector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Aruco.o"
	@echo "... src/Aruco.i"
	@echo "... src/Aruco.s"
	@echo "... src/Benchmark.o"
	@echo "... src/Benchmark.i"
	@echo "... src/Benchmark.s"
	@echo "... src/CameraViewPoints.o"
	@echo "... src/CameraViewPoints.i"
	@echo "... src/CameraViewPoints.s"
	@echo "... src/HighLevelLinemod.o"
	@echo "... src/HighLevelLinemod.i"
	@echo "... src/HighLevelLinemod.s"
	@echo "... src/HighLevelLinemodIcp.o"
	@echo "... src/HighLevelLinemodIcp.i"
	@echo "... src/HighLevelLinemodIcp.s"
	@echo "... src/Kinect2.o"
	@echo "... src/Kinect2.i"
	@echo "... src/Kinect2.s"
	@echo "... src/ModelBuffer.o"
	@echo "... src/ModelBuffer.i"
	@echo "... src/ModelBuffer.s"
	@echo "... src/ModelImporter.o"
	@echo "... src/ModelImporter.i"
	@echo "... src/ModelImporter.s"
	@echo "... src/OpenglRender.o"
	@echo "... src/OpenglRender.i"
	@echo "... src/OpenglRender.s"
	@echo "... src/PoseDetection.o"
	@echo "... src/PoseDetection.i"
	@echo "... src/PoseDetection.s"
	@echo "... src/TemplateGenerator.o"
	@echo "... src/TemplateGenerator.i"
	@echo "... src/TemplateGenerator.s"
	@echo "... src/defines.o"
	@echo "... src/defines.i"
	@echo "... src/defines.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
	@echo "... templateGeneration.o"
	@echo "... templateGeneration.i"
	@echo "... templateGeneration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

